// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.1
//
// <auto-generated>
//
// Generated from file `HelloIce.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package vip.wush.ice.demo.demo;

public class _HelloIcePrxI extends com.zeroc.Ice._ObjectPrxI implements HelloIcePrx
{
    public static final long serialVersionUID = 0L;
}
